# Sample command to start this up
# docker build -f Dockerfile.dev -t lokion/productcatalog . && docker run -p 8080:8080 -p 50051:50051 --name productcatalog lokion/productcatalog

FROM golang:1.12

WORKDIR '/app'

# Copy over the dependencies declaration and install them
COPY go.mod .
RUN go get -d -v ./...

# Copy over the application code
COPY . .
RUN go build -o main cmd/server/main.go

EXPOSE 8080
EXPOSE 50051

CMD ["/app/main"]