FROM golang:1.12

WORKDIR '/app'

# Copy over the dependencies declaration and install them
COPY go.mod .
RUN go get -d -v ./...

# Copy over the application code
COPY . .
RUN go build -o main cmd/server/main.go

EXPOSE 8080
EXPOSE 50051

CMD ["/app/main"]